---
name: cron
on:
  schedule:
    - cron: '17 * * * *'
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - run: bundle update
      - run: bundle exec rake rubocop
      - run: |
          bin/mergem --verbose \
            --token=${{ secrets.TOKEN }} \
            --repo=volodya-lombrozo/jtcop \
            --repo=volodya-lombrozo/hg-revision-plugin \
            --repo=objectionary/jeo-maven-plugin \